<?php

/**
 * Implementation of hook_views_api().
 */
function occuspace_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'occuspace') . '/views',
  );
}

/**
 * Implements hook_menu().
 */
function occuspace_menu() {
  /* proxy settings */
  $items['admin/config/system/occuspace']
    = array(
    'title' => 'Occuspace report settings',
    'description' => 'Configure settings for Occuspace reports',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('occuspace_settings'),
    'access arguments' => array('administer occuspace settings'),
    'weight' => -10,
  );

  return $items;
}

function occuspace_permission() {
  $modperms = array(
    'administer occuspace settings' => array(
      'title' => t('Administer Occuspace reports'),
    ),
  );
  return $modperms;
}

/**
 * @return mixed
 */
function occuspace_settings() {
  $form = array();
  $form['occuspace_server'] = array(
    '#type' => 'textfield',
    '#title' => t('Occuspace Server'),
    '#default_value' => variable_get('occuspace_server', ""),
    '#description' => t("Server used for the Occuspace api"),
    '#required' => TRUE,
  );
  $form['occuspace_server_busy'] = array(
    '#type' => 'textfield',
    '#title' => t('Occuspace Server for Busyness'),
    '#default_value' => variable_get('occuspace_server_busy', ""),
    '#description' => t("Server used for the Occuspace api for the busyness of the zone. Don't put in the number or the word now."),
    '#required' => TRUE,
  );
  $form['occuspace_authID'] = array(
    '#type' => 'textfield',
    '#title' => t('Occuspace Authorization ID'),
    '#default_value' => variable_get('occuspace_authID', ""),
    '#description' => t("The authorization ID for Occuspace"),
    '#required' => TRUE,
  );
  $form['occuspace_count_label'] = array(
    '#type' => 'textfield',
    '#title' => t('Occuspace Count Label'),
    '#default_value' => variable_get('occuspace_count_label', ""),
    '#description' => t("The label for the chart indicating the number of people occupying a zone"),
    '#required' => TRUE,
  );
  $form['occuspace_available_label'] = array(
    '#type' => 'textfield',
    '#title' => t('Occuspace Available Label'),
    '#default_value' => variable_get('occuspace_available_label', ""),
    '#description' => t("The label for the chart indicating the number of people that can still enter the zone"),
    '#required' => TRUE,
  );
  $form['occuspace_slice_text_color'] = array(
    '#type' => 'textfield',
    '#title' => t('Occuspace Slice Text Color'),
    '#default_value' => variable_get('occuspace_slice_text_color', 'white'),
    '#description' => t("The color for the text on the pie slices (hex or color name)."),
    '#required' => TRUE,
  );
  $form['occuspace_piehole'] = array(
    '#type' => 'textfield',
    '#title' => t('Occuspace Piehole'),
    '#size' => 5,
    '#default_value' => variable_get('occuspace_piehole', 'white'),
    '#description' => t("The blank space in the middle of the pie chart. Enter a number between 0 and 1. To shut your piehole, enter 0."),
    '#required' => TRUE,
  );
  return system_settings_form($form);
}


function occuspace_chart_definition_alter(&$definition, $chart, $chart_id) {
    $chartChoice = $chart['#view']->query->options['occuspace_chart_choice'];
    if ($chart['#chart_type'] == 'pie' || $chartChoice == 'yesGauge') {
        if (strpos($chart_id, 'occuspace') !== false) {
            $occuspace_count_label = variable_get('occuspace_count_label', "Occupied");
            $occuspace_available_label = variable_get('occuspace_available_label', "Available");
            $occuspace_slice_text_color = variable_get('occuspace_slice_text_color', "White");
            $occuspace_piehole = variable_get('occuspace_piehole', "0.65");
            $data = array();
            $data[] = array('first', 'second');
            $count = 0;
            $capacity = 0;
            $percs = 0;
            $numOfRecords = 0;
            $chartChoice = ($chartChoice == 'yesGauge') ? 'Gauge' : 'PieChart';
            foreach ($chart['#view']->result as $d) {
                $numOfRecords ++;
                $percs += $d->percentage;
                $count += $d->count;
                $capacity += $d->capacity;
            }
            $percentage = $percs/$numOfRecords;
            if ($chartChoice == 'PieChart') {
                $available = ($capacity - $count);
                $data[] = array('', $capacity);
                $data[] = array($occuspace_count_label, $count);
                $data[] = array($occuspace_available_label, $available);

                $definition['options']['pieHole'] = $occuspace_piehole;
                $definition['options']['pieStartAngle'] = 90;
                $definition['options']['slices'][0] = [
                    'color' => 'transparent',
                    'enableInteractivity' => FALSE,
                ];
                $definition['options']['innerSize'] = '50%';
                $definition['options']['pieSliceTextStyle']['color'] = $occuspace_slice_text_color;
                $definition['options']['pieSliceTextStyle']['text-anchor'] = 'middle';
                $definition['options']['pieSliceText'] = 'percentage';
                $definition['options']['animation']['startup'] = TRUE;
                $definition['options']['animation']['duration'] = 10000;
                $definition['options']['animation']['easing'] = 'inAndOut';

                // See Definition before
                dsm($definition);

                // here is where we override highcharts. I kept the same settings above in case some can apply to highcharts.
                // At first I had this code higher trying to set it up completely separately than google charts code.
                if ($chart['#chart_library'] == 'highcharts') {
                    $definition['plotOptions']['pie']['startAngle'] = 90;
                    $definition['plotOptions']['pie']['size'] = '50%';
                    $definition['plotOptions']['series']['dataLabels']['enabled'] = TRUE;
                    $definition['series']['type'] = 'pie';
                    $definition['series']['name'] = 'TEST';
                    $definition['series']['innerSize'] = '50%';
                    $definition['series']['data'] = $data;
                    // see $definition after
                    dsm($definition);
                }
            }
            else {
//                $data[] = array($definition['options']['title'], $count);
                // try to add gauge js if using highcharts. This is not tested yet.
                // Was trying to get donut working first.
                if ($chart['#chart_library'] == 'highcharts') {
                  drupal_add_js('https://code.highcharts.com/modules/solid-gauge.js', 'external');
                }
                $data[] = array(round($percentage) . '%', $count);
                $definition['options']['greenColor'] = '#00B239';
                $definition['options']['yellowColor'] = '#FFC300';
                $definition['options']['redColor'] = '#B20000';
                $definition['options']['greenFrom'] = 0;
                $definition['options']['greenTo'] = $capacity*.75;
                $definition['options']['yellowFrom'] = $capacity*.75;
                $definition['options']['yellowTo'] = $capacity*.9;
                $definition['options']['redFrom'] = $capacity*.9;
                $definition['options']['redTo'] = $capacity;
                $definition['options']['max'] = $capacity;
            }
            $definition['visualization'] = $chartChoice;
//            $definition['options']['legend']['position'] = 'top';
            $definition['data_labels'] = TRUE;
            $definition['data'] = $data;
        }
    }
}
