<?php

/**
 * Implementation of hook_views_api().
 */
function occuspace_views_api() {
  return array(
    'api' => 3.0
  );
}

/**
 * Implements hook_menu().
 */
function occuspace_menu() {
  /* proxy settings */
  $items['admin/config/system/occuspace']
    = array(
    'title' => 'Occuspace report settings',
    'description' => 'Configure settings for Occuspace reports',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('occuspace_settings'),
    'access arguments' => array('administer occuspace settings'),
    'weight' => -10,
  );

  return $items;
}

function occuspace_permission() {
  $modperms = array(
    'administer occuspace settings' => array(
      'title' => t('Administer Occuspace reports'),
    ),
  );
  return $modperms;
}

function occuspace_settings() {

  $form = array();

  $form['occuspace_server'] = array(
    '#type' => 'textfield',
    '#title' => t('Occuspace Server'),
    '#default_value' => variable_get('occuspace_server', ""),
    '#description' => t("Server used for the Occuspace api"),
    '#required' => TRUE,
  );

  $form['occuspace_authID'] = array(
    '#type' => 'textfield',
    '#title' => t('Occuspace Authorization ID'),
    '#default_value' => variable_get('occuspace_authID', ""),
    '#description' => t("The authorization ID for Occuspace"),
    '#required' => TRUE,
  );

  return system_settings_form($form);

}
